### ISSUE TITLE
generate mixed_lm_example.html again

### ISSUE THREAD

**Issue by diegodlh** [statsmodels/statsmodels.github.io#19]
I am not sure what I can do to help solve this, as I don't know what the correct procedure is for updating html example notebooks generated from ipynb files. The mixed_lm_example.html notebook was generated with errors, as it appears that rpy2 was not available at runtime. Of course I could generate the right html and issue a pull request, but I'm not sure that's the way to do it. Please, let me know

**Comment by TomAugspurger** [comment]
This is fixed with the latest: http://www.statsmodels.org/stable/examples/notebooks/generated/mixed_lm_example.html

though there are quite a few warnings. If you have the time / interest, you could open an issue on `statsmodels/statsmodels` to see if those could be fixed.
