### ISSUE TITLE
Dead  link (ANOVA)

### ISSUE THREAD

**Issue by n8willis** [statsmodels/statsmodels.github.io#27]
It's not entirely clear from looking at the org repos where this sort of thing ought to be reported, but I was reading the github-io site this morning and ran into a 404 dead-link situation. On https://www.statsmodels.org/stable/anova.html the end of the 'Examples' section says 
```
A more detailed example for anova_lm can be found here:
- [ANOVA](https://www.statsmodels.org/stable/examples/notebooks/generated/interactions_anova.html)
```

... which is a dead link. Guessing by the URI pattern, that's auto-generated somehow, so hopefully it's fixable. But right now, it's broken.

And, if it's a generated-links issue, then it's plausible to be concerned that there are other such links that may similarly be broken. I haven't gone on a hunt for them.

**Comment by bashtage** [comment]
It is working in the dev docs here: https://www.statsmodels.org/devel//examples/notebooks/generated/interactions_anova.html

This will be automatically fixed when 0.14 is released in a week or so.

**Comment by n8willis** [comment]
Okay; I'm curious: do you know what caused the break?

(Good for my own browsing, to be able to read the contents, but I kinda want to know ... as someone who maintains documentation myself, and as someone who might run into other broken links here & wants to get a step ahead if that happens)

**Comment by bashtage** [comment]
There was a bug in the notebook due to changes in upstream projects that make it fail to render.

**Comment by bashtage** [comment]
Just closing since this has been addressed, not to stop conversation.
